### ISSUE TITLE
uuid校验失败

### ISSUE THREAD

**Issue by rehack** [Misaka-blog/cf-wkrs-pages-vless#14]
生成的vmess uuid都通不过
![Snipaste_2024-04-20_20-35-49](https://github.com/Misaka-blog/cf-wkrs-pages-vless/assets/9047357/2aba9cdc-7a92-4b1e-875a-f8a4dfb19e14)
![Snipaste_2024-04-20_20-40-22](https://github.com/Misaka-blog/cf-wkrs-pages-vless/assets/9047357/39b94d45-dcd2-4b4d-96e8-04cf9269fdf5)
reg有问题，中间不是匹配4位吗？
const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

**Comment by Misaka-blog** [comment]
好奇你哪里生成的 uuid

**Comment by rehack** [comment]
> 好奇你哪里生成的 uuid

就在线生成uuid的工具，比如https://intmainreturn0.com/v2ray-config-gen/#
可能这不是标准的version4 uuid,你的正则只兼容version4

**Comment by Misaka-blog** [comment]
> > 好奇你哪里生成的 uuid
> 
> 就在线生成uuid的工具，比如https://intmainreturn0.com/v2ray-config-gen/# 可能这不是标准的version4 uuid,你的正则只兼容version4

就只能用标准的 uuid v4
